### ISSUE TITLE
RecurrenceValue Bitmap

### ISSUE THREAD

**Issue by stevex86-old** [asusoda/TaskDevilFall#36]
Replace the current method for storing RecurrenceValue with a bitmap format.

**Comment by stevex86-old** [comment]
Implemented I but need write access to push.

**Comment by cassierecher** [comment]
Access should be enabled now - my bad. Please create a new branch to commit this to - the general flow once things ramp up will be individual feature branches that merge into milestone branches.

**Comment by stevex86-old** [comment]
Pushed to recurrence_bitmasks branch.
