### ISSUE TITLE
Repository access denied to non-administrative team members.

### ISSUE THREAD

**Issue by stevex86-old** [asusoda/TaskDevilFall#37]
I tried to push a commit earlier, but the push failed because apparently I don't have write access to the repo.

![screen shot 2014-09-04 at 10 35 40 pm](https://cloud.githubusercontent.com/assets/6069481/4160577/8ceca7ba-34be-11e4-9415-29f407a3333f.png)

After some investigation, I found out that despite being a member of the ASU SoDA organization on GitHub and a member of the Task-Devil-Team, the team itself does not provide access to any repositories.

![screen shot 2014-09-04 at 10 38 20 pm](https://cloud.githubusercontent.com/assets/6069481/4160596/066f68e8-34bf-11e4-8081-26569254d19a.png)

Should be a pretty painless fix. Sorry for posting so late at night!

**Comment by cassierecher** [comment]
Fixed - Didn't have team access configured correctly
